# Generated by Django 3.0.4 on 2020-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200504_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
